### ISSUE TITLE
Responsive Grids

### ISSUE THREAD

**Issue by ManiAkasapu** [ducksboard/gridster.js#116] opened 2013-01-25 16:19 UTC
Make the grid responsive along with resolution of the screen. If I fix no.of widgets per a row let them to occupy whole screen width.

Thanks

**Comment by ursomniac** [comment] 2013-01-28 16:25
We have need for this as well.  

Some people have commented that responsiveness counteracts the dragging feature.   I disagree - responsiveness is just a "canned dragging operation"; in other words, it is COMPLETELY doable with the present code to take the initial layout and manually move all of the necessary widgets to positions that would be in a less-wide configuration.   Having the code do this as the window is resized is no different - you just end up with a new "default" configuration to start from.

NOW - if by "responsive" you only mean "based on the browser size I want a different layout" (e.g., iPhone vs tablet vs desktop) - then you can do that programatically (at least that's how we're planning to handle it): dynamically alter the parameters based upon the window size on load (which won't handle dynamically resizing the window but that's less of an issue than understanding that the browser size definitely changes among devices).

**Comment by A973C** [comment] 2013-02-12 08:39
:+1: for a responsive layout!

Actually, all widgets position is predefined by element attributes (data-row, data-col,...). In a responsive mode, we could have 2 options: user positioning (like actually) or auto positioning. In this case, grid elements will be automatically positioned in order to fit the width and height user screen (like Isotope plugin & Co).

And if Santa Claus can read me, the auto positioning should take care of the element width. In the demo available on your home screen, we can see element with different sizes. So, for example, 2 bigs squares should not be side by side, ... (just to keep a nice visual aspect).

But of course, all this positions could be customized by user.

Cheers!

**Comment by andyl** [comment] 2013-05-09 20:14
+1 for responsive layout!

**Comment by activeworx** [comment] 2013-05-22 13:32
+1 for responsive layout! would love to see widgets off screen be wrapped to the following row like what happens when you start Gridster when the visible size is smaller then the saved size.

**Comment by MartinWeise** [comment] 2013-06-12 15:42
Would really like to have an responsive gridster.js!
How can I make this on my own, any ideas?
Please send me to hi@martinweise.at!

**Comment by shaundon** [comment] 2013-06-21 15:01
I've achieved what I'm calling 'pseudo-responsiveness' with a few small hacks. It's not perfect, but it should suffice for my needs!

``` javascript
// Before initialising gridster, get window width.
var width = $(window).width();

// Use the width to determine how many columns to display.
var columns = 6;
if (width < 900)
  columns = 5;
else if (width < 750)
  columns = 4;
// ..etc, down to only two columns.

// Positions have been loaded from a database, so get all that
// are set to be further along than the width of the grid.
var tooFar = $('.gridster li').filter(function () {
  return $(this).data('col') > columns;
});

// For each widget that's too far along, reset its position.
// Gridster will rearrange the others to accomodate this.
$(tooFar).each(function () {
  $(this).attr('data-col', '1');
});

// Get all widgets that are now too wide for the screen.
var tooBig = $('.gridster li').filter(function () {
  return $(this).data('sizex') > columns;
});

// Hide each of these.
$(tooBig).each(function () {
  $(this).hide();
});

/*
 * Here you should initialise gridster as normal,
 * ensuring to use 'columns' as the value for 'min_cols'.
 */

/*
 * Disable dragging on small devices, so that
 * the layout saved to the DB won't be affected by people
 * on smaller screens. 
 */

```

**Comment by vieron** [comment] 2014-06-16 13:18
Duplicate of #5

**Closed as completed** 2014-06-16 13:18 UTC
