### ISSUE TITLE
Question : How can I resize a widget without messing up the all grid ?

### ISSUE THREAD

**Issue by ghost** [ducksboard/gridster.js#21] opened 2012-08-10 11:19 UTC
Hi dear Gridster team !

I have a new issue on my zoning tool :

I made a little "Widget edit" function so I can change the widget size. I would like to know if there is a clean way to do it.

For instance in my tool http://floflow.me/_sites/zoning/, when you try to resize the "Logo" widget (click on the pen) height from 2 rows to 4 rows, the menu under doesn't move so the grid is unusable :/

Thanks in advance for your help !
Flow

**Comment by vieron** [comment] 2012-08-10 14:46
This is a duplicate of #15, so i'm going to close this issue.

**Closed as completed** 2012-08-10 14:46 UTC
Labels: feature-request

**Comment by ghost** [comment] 2012-08-10 14:51
thank you for feedback and sorry for duplicated question
