### ISSUE TITLE
Dragging a wide block can cause blocks to overlap other blocks

### ISSUE THREAD

**Issue by daniel-nelson** [ducksboard/gridster.js#4] opened 2012-07-30 18:36 UTC
Easiest to convey this with a video: http://screencast.com/t/05wwm3l9Yfp

**Comment by peterchon** [comment] 2012-07-30 19:58
Still not showing up on Chrome

**Comment by Quantumplation** [comment] 2012-08-10 03:06
I've reproduced this in Chrome:

http://i.imgur.com/zJH2R.png 
The wide block at the bottom left is dragged downward.
http://i.imgur.com/fx0kW.png

**Comment by Smashr** [comment] 2012-08-26 13:38
+1 for fixing this issue. ... running into major problems with large blocks . ! ... I've noticed that the issue is more pronounced in handheld devices with touch (iPad). This occurs in almost all browsers (Chrome and FF tested).

There's also another issue where moving around a large block will cause other blocks to not automatically adjust to the topmost available space and they stay a row or two below the space where they would otherwise fit, the blocks do not adjust position to the space directly above even when there is ample space above these small blocks. This issue is probably related to the large block overlap issue.

**Comment by ghost** [comment] 2013-01-10 08:41
+1 We also have this problem! plase fix this issue...

**Comment by goldnead** [comment] 2013-01-15 09:41
+1

**Comment by ghost** [comment] 2013-01-25 11:26
This is a way to reproduce the problem:

![Untitled-1](https://f.cloud.github.com/assets/2869722/97166/05f01716-66e2-11e2-974c-84c08c6910af.jpg)
![Untitled-2](https://f.cloud.github.com/assets/2869722/97163/05b76e52-66e2-11e2-8226-fd6ae6b60045.jpg)
![Untitled-3](https://f.cloud.github.com/assets/2869722/97164/05b655a8-66e2-11e2-84a8-999dd7c6d50b.jpg)
![Untitled-4](https://f.cloud.github.com/assets/2869722/97165/05bb48b0-66e2-11e2-9974-c9e0baf64240.jpg)

**Comment by ghost** [comment] 2013-01-30 08:03
Let us know if there is a way to fix it or if we have to start quitting using grister.
This bug is making gridster unusable, we are willing to pay to get this fixed!

**Comment by ghost** [comment] 2013-03-15 11:10
```
fn.move_widget_down = function($widget, y_units) {
    if (y_units < 0) 
        return;
```

..and everything is working again!

**Comment by otisg** [comment] 2013-05-22 17:47
Btw. we are seeing the same problem...

**Comment by maxgalbu** [comment] 2013-07-04 17:39
thanks @bastianonm :+1:

**Comment by otisg** [comment] 2013-07-04 19:09
@vieron any chance @bastianonm's PR could be merged in?

**Comment by argshook** [comment] 2013-08-19 19:18
Thank you, @bastianonm, this was causing me headaches! I think this change should definitely be merged.

**Comment by vieron** [comment] 2013-10-26 18:00
Merged here https://github.com/ducksboard/gridster.js/commit/31fd8d6ba893e4c39b91ba30d429e37f3da30b24

**Closed as completed by vieron** 2013-10-26 18:00 UTC
Labels: bug

**Comment by Cryrivers** [comment] 2014-06-26 10:31
This issue hasn't been solved perfectly yet. I can still get blocks overlapping even if none of blocks is dragged. They just overlap after the creation with API `add_widget`. I'll upload screencast soon.
