### ISSUE TITLE
connect grids

### ISSUE THREAD

**Issue by Roywcm** [ducksboard/gridster.js#133] opened 2013-03-01 15:00 UTC
Hi,

Is it possible to connect two grids?
So, you can drag and drop a widget from one to the other grid?

I'll hope this is possible! Really need this.

Roy

**Comment by FRickReich** [comment] 2013-03-01 17:53
splendid idea! +1

**Comment by tuimz** [comment] 2013-03-01 19:29
+1 Would be really great!

**Comment by lukju** [comment] 2013-03-23 15:31
+1
would be very useful, because in a gridster with more than a couple of widgets the drag-and-drop game becomes difficult and is similar to a puzzle.
using multiple gridsters with the possibility to drag and drop widgets from one gridster to the other would solve this issue.
i guess the crew who developed the Window 8 start screen had exactly the same thoughts...

**Comment by nuwanbando** [comment] 2013-04-05 13:18
+1 great idea

**Comment by JoschaP** [comment] 2013-04-11 22:34
+1

**Comment by saenzramiro** [comment] 2013-04-15 16:10
+1

**Comment by JoschaP** [comment] 2013-05-01 07:09
+1

**Comment by jmaag** [comment] 2013-06-20 18:10
+1

**Comment by rcesare** [comment] 2013-07-23 10:29
+1

**Comment by bpbhat77** [comment] 2013-09-03 06:40
+1

**Comment by dustinbolton** [comment] 2014-05-19 08:07
+1

**Comment by vieron** [comment] 2014-06-16 12:47
Duplicate of #68

**Closed as completed by vieron** 2014-06-16 12:47 UTC
Labels: feature-request
