### ISSUE TITLE
Exchange widgets from one gridster grid to a different gridster grid and vice versa

### ISSUE THREAD

**Issue by davidpelayo** [ducksboard/gridster.js#332] opened 2014-03-19 17:15 UTC
It would be nice Gridster would support the developer to exchange widgets from two existing gridsters on the DOM.

Like this, you can have two grids initialised with different set of widgets (and coloured, if wanted), and you would be moving a widget from one grid to the other, or vice versa.

From what I've been seeing, there is no way to support these kind of behaviours using the built-in library methods.

**Comment by tkorkalainen** [comment] 2014-04-19 18:55
This is something I would also like to see in a future release.

**Comment by Superdrac** [comment] 2014-05-09 12:50
I think it should be possible with the drag & drop jquery method implementation. For exemple, when you press "ctrl" and that you dragg a gridster widget, you are able to move it onto another grid. On drop event, you call remove widget on the first grid and you call add_widget on the new grid, with all the widget properties. 

Sure it's possible to make it by this way.

**Comment by vieron** [comment] 2014-06-16 12:53
Duplicate of #68

**Closed as completed by vieron** 2014-06-16 12:53 UTC
