### ISSUE TITLE
In latest version of Chrome if any of the widget is deleted than rest of widgets overlaps and starts shrinking

### ISSUE THREAD

**Issue by viking916** [ducksboard/gridster.js#372] opened 2014-05-13 14:43 UTC
Whenever i delete any widget from gidster it causes other widgets to resize and overlap. This is only happening in latest version of Chrome. It works fine in latest FF and ie8 and above.

Following are the images of the layout before and after the delete:

Before deleting any widget: http://imgur.com/0JzXGdj

After deleting widget#1,here you will be able to see that bottom widget is overlapping top widget. Both the widgets starts to misaligned and shrink: http://imgur.com/Tiri6Yv

i use following lines of code to delete widget:
  var gridster = $(".gridster ul").gridster().data('gridster');
     gridster.remove_widget($('#geoChartLi'));

Here "geoChartLi" is the id of li element/widget of gridster.

i noticed that following changes in terms of css:
[data-sizex="1"] {
width: unexpected new value ;
}
[data-sizey="1"] {
height: unexpected new value;
}

[data-col="2"] {
left: unexpected new value;
}

[data-row="2"] {
top: unexpected new value;
}

[data-sizey="2"] {
min-height:unexpected new value ;
}

There might be more properties thats getting affected its just that i have noticed this few. 

Please help. Thanks!

**Comment by hrosenbauer** [comment] 2014-05-19 07:48
Could you create e.g. a jsfiddle for this testcase? We are using gridster and I don't have any problems using Chrome Canary (latest nightly build) or stable.

**Comment by viking916** [comment] 2014-05-20 15:18
Yes i'll create fiddle and post it here. Thanks

**Comment by vieron** [comment] 2014-06-16 10:52
Can't reproduce it. Please update a jsfiddle example if problem persists.
Closing...

**Closed as completed by vieron** 2014-06-16 10:52 UTC
