### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by centerofme** [ducksboard/gridster.js#244] opened 2013-10-29 19:39 UTC
this plugin is amazing i'd love it even more if it were responsive :)

**Comment by beeftornado** [comment] 2013-11-01 01:24
I've made it responsive with a plugin I made without touching the original source with help from other commenters. I will integrate it as a feature and submit pull request to the author. It behaves as one would expect it to, meaning it responds to window resizing and mobile devices with the vertical flow. I will post the plugin as soon as I clean it up.

**Comment by smajl** [comment] 2013-11-05 12:58
@beeftornado I am really looking forward to your plugin. :) Can you please explain how exactly are you handling the "responsivenes"? Do you dynamically change the base dimension (this is how I currently do it) or maybe change number of columns and move overflowing widgets on a new row? Or something else?

**Comment by beeftornado** [comment] 2013-11-05 20:09
@smajl The plugin to the plugin hooks into the window's resize event and calculates the number of columns it should have, using Bootstrap's defined width to go into a "mobile mode." In this mode, it is really just a one column grid, with CSS defining the width of that one column to be the size of the container, thus once you scale down below that threshold, the widget width changes with the screen (instead of column count changing). I overrode the generation of CSS styles to include this extra stanza, which was just a `@media (max-width: 768px) { blah blah }`. As the window is being resized, I am checking if any of the widgets column number plus the the width of the widget goes beyond the total number of columns and if so then I have to move it. The reverse also has to be true, where if the grid is to get bigger, the user would expect to see widgets start making their way back up the grid and not have to manually restore their widget placements. 

I don't touch the base dimensions unless going between "modes." I have been manipulating the margins, which I know sounds odd, but worked. I'm currently playing with another method right now, which looks like it could pan out. 

After changing the margins, I went through the grid and did the widget replacement. 

This is all a bit difficult to explain because frankly, the process by which I'm doing it is hacky. And while it works, the code is an embarrassment. Once I can get it to logically flow, it will be easier to explain, but by then I will also be able to just have you read it.

**Comment by smajl** [comment] 2013-11-11 13:38
@beeftornado Sounds great, thx for reply. Looking forward to see that in action. Widgets reversing position is super cool.

**Comment by beeftornado** [comment] 2013-11-16 00:22
Here is the plugin as it stands. I'm currently working on removing some of the overhead and unnecessary bits. I'm also working on a patch of the original source to add it as a feature.

https://gist.github.com/beeftornado/7494043

**Comment by philoyang** [comment] 2014-01-21 06:28
@beeftornado Could you give a full demo, please? I am looking forward to that as the code https://gist.github.com/beeftornado/7494043 can't work. I get some errors with that code. Thanks

**Comment by galievruslan** [comment] 2014-02-13 17:46
@beeftornado Hi. Also use gridster. I really like it. But lacks flexibility. For example, when the browser size is changed. I see you are trying to add flexibility to gridster. Tell me how to do it?

**Comment by zeldich** [comment] 2014-02-18 07:52
+1 for responsiveness!

**Comment by NirHemed** [comment] 2014-02-18 08:16
+1

**Comment by proleskovskiy** [comment] 2014-02-25 11:37
It would be great for gridster to rearrange blocks when browser size changed.
+1 responsiveness

**Comment by mastastealth** [comment] 2014-02-28 14:48
+1

**Comment by andreasanta** [comment] 2014-02-28 15:16
+1

**Comment by justiny** [comment] 2014-03-03 01:41
+1

**Comment by BartNetJS** [comment] 2014-03-05 19:26
+1

**Comment by BartNetJS** [comment] 2014-03-06 18:40
Does anyone have the solution from @beeftornado working?

**Comment by skozz** [comment] 2014-03-06 19:14
+1

**Comment by nadeesha** [comment] 2014-03-07 12:30
I'd love a native gridster solution, but so far I haven't been able to get something like this working. 

However, I created my own plugin that will generate responsive bootstrap layouts from gridster. Here's the [github](https://github.com/ncthis/gridster-bootstrap) and the [demo](https://rawgithub.com/ncthis/gridster-bootstrap/master/demo/index.html).

**Comment by a-iasevoli** [comment] 2014-04-09 12:34
+1

**Comment by gcphost** [comment] 2014-04-15 05:11
+1 for this, ncthis's method seems to only duplicate the layout to another div, not update the controllable layout to be responsive.

**Comment by nadeesha** [comment] 2014-04-15 05:15
@gcphost, true. I just needed a way to use gridster to generate a responsive layout, and not make gridster itself responsive.

**Comment by gcphost** [comment] 2014-04-19 10:12
here's my solution:
https://github.com/gcphost/gridster-responsive

comes with a few extra goodies like minimize/max/close and edit the color of the title.

made for bootstrap widgets

**Comment by vieron** [comment] 2014-06-16 13:17
Duplicate of #5

**Closed as completed by vieron** 2014-06-16 13:17 UTC
