### ISSUE TITLE
Drag 's not working

### ISSUE THREAD

**Issue by sozonovalexey** [ducksboard/gridster.js#207] opened 2013-07-28 18:25 UTC
Hello! 
Drag does not work on the customer's computer (no errors) but on my all is well and example on http://gridster.net/ also does not work! It's a magic!

**Comment by sozonovalexey** [comment] 2013-07-28 18:26
How can i fix it?

**Comment by OClement** [comment] 2013-07-29 18:35
Can you see any kind of error or logs from the console?
What browser did you test in? Is Javascript  enabled in the browser?

---

I personally got the "same" problem:
A project I am working on is working fine on my work laptop (OSX Mountain Lion, Chrome, etc. + Win7 IE9 in VMware), but not on my home PC (win8, no go in Chrome, IE or FF, all latest versions)

No logs, no errors no nothing -> Same goes for the demo on gridster.net Other demos around the web won't work either.

It IS working fine on my girlfriend's PC, same setup as me (Win8 and all).

So it definitely looks like a problem specific to my machine but I can't figure out why. Checked everything I could and all looks fine.

**Comment by sozonovalexey** [comment] 2013-07-29 18:44
No errors! Yes Javascript is enabled. Windows 7 + Chrome the last version. 

On my PC Win8 + the same Chrome it is working fine!

**Comment by sozonovalexey** [comment] 2013-07-29 18:45
But in ie it works good

**Comment by barisonal** [comment] 2013-07-30 09:30
Hi guys, it doesn't work for us either :( There is no any error message in console, no any alert etc... Browsers: Chrome, Firefox OS: Windows 7

**Comment by barisonal** [comment] 2013-07-30 09:31
Hi guys, it doesn't work for us either :( There is no any message in console or alert etc.  Javascript is enabled and I tried it in Chrome and Firefox. Os: Win7

**Comment by JpEncausse** [comment] 2013-08-10 15:27
Got the same issue, I think it is related to latest Chrome touch event that prevent click on Gridster. I don't know if there is workaround

**Comment by OClement** [comment] 2013-08-10 15:49
I wouldn't be so sure (chrome issue)
I have two PC setup in the same way (win8, latest chrome) and both behave differently. It won't work on any browser on my PC, while it's working on all browsers on my GF's PC

There must be some tool or something I installed that altered a Win's config I don't know

Working fine on MacBook Pro too

Envoyé de mon iPhone

**Comment by JpEncausse** [comment] 2013-08-10 15:53
One thing I installed on Win7 since I discover the issue is LeapMotion which add "touch feature" on OS layer

**Comment by krazyjakee** [comment] 2013-08-14 12:02
Dupe of https://github.com/ducksboard/gridster.js/issues/203

**Comment by sozonovalexey** [comment] 2013-09-09 14:47
the problem is still actual!

**Comment by edokan** [comment] 2013-09-13 15:19
I also confirm problem exists on Both Chrome and Firefox. It not a coincidence that I have installed Leap Motion software on my Windows 7 computer.

To reproduce just install leap motion software from https://www.leapmotion.com/setup. Issue does not need a device to reproduce. Just install and reboot.

**Comment by simonjutz** [comment] 2013-09-17 09:12
I confirm that the problem exists in both firefox and chrome when having installed the Leap Motion Software. As my software doesn't need any touch input as it is only used on desktop computers, i dropped the feature in jquery.gridster.js by changing line 378:

var isTouch = !!('ontouchstart' in window);

to

var isTouch = false;

This solves the problem, but also drops the touch support. I'm sure there will be a better solution, e.g. by checking if the leap motion software is installed, but this works for me as a temporary workaround.

Dear gridster team, keep up the good work! :)

**Comment by OClement** [comment] 2013-09-27 16:07
So it looks like the issue is caused by something related to touch/hid device drivers or something;

I have (had) this issue but don't have a Leap Motion nor did i installed its drivers. So I ended up looking into whatever I had installed and turns out I had `Microsoft Mouse and Keyboard Center` installed, which is a driver for MS keyboards and mice (duh).

Uninstalled it, restarted Chrome and BOOM! It worked

Hopefully this will help a few people out there too; Obviously this doesn't solve the problem as you can't ask all your users to remove their whatever-drivers indeed, but it might help clarify this issue

**Comment by davidpelayo** [comment] 2014-02-12 09:45
Dropping isn't working on Safari (Mac OS Maverics, Windows 7, ...). You can start dragging a widget but then not placing it wherever you want.

**Comment by dustmoo** [comment] 2014-02-12 16:33
Do you see any javascript errors in your console?

**Comment by davidpelayo** [comment] 2014-02-12 17:06
No console errors. Just not working drop behaviours, kind of event cancelled or so, but didn't have the chance to debug. I will tell you more when I debug.

**Comment by wildgeeza** [comment] 2014-02-19 16:42
Ditto, dropping not working, where drag works fine. Similar, no console errors, but I have noticed if you rescale, then the drop works after dragging

**Comment by eemmzz** [comment] 2014-05-21 20:03
I see this issue on my ultrabook. For me it is due to the touchscreen this machine has as the demo works if I use the screen but not my touchpad/mouse

**Closed as completed** 2014-06-16 17:06 UTC
Labels: bug
