### ISSUE TITLE
drag onto other draggable

### ISSUE THREAD

**Issue by eperler123** [ducksboard/gridster.js#341] opened 2014-04-03 15:38 UTC
hello

is it possible to drag and drop an item onto an existing droppable..

i.e... i drag a widget onto the grid... and i want to drag text onto the widget and make it part of its htmlContent.. so that when i drag the widget.. the text drags with it

thanks in advance

**Comment by vieron** [comment] 2014-06-16 13:40
Duplicate of #68

**Closed as completed by vieron** 2014-06-16 13:40 UTC
