### ISSUE TITLE
Responsive based on Screen Size

### ISSUE THREAD

**Issue by abishekrsrikaanth** [ducksboard/gridster.js#258] opened 2013-11-13 12:06 UTC
Does Gridster support the feature to be responsive based on the size of the screen. If yes, how can I do that?

**Comment by tOmoness** [comment] 2013-11-13 19:42
@abishekrsrikaanth, this may help #77.

**Comment by vieron** [comment] 2014-06-16 13:18
Duplicate of #5

**Closed as completed by vieron** 2014-06-16 13:18 UTC
