### ISSUE TITLE
Dynamic column number based on parent element size?

### ISSUE THREAD

**Issue by ScottBeeson** [ducksboard/gridster.js#374] opened 2014-05-22 13:37 UTC
How can I configure gridster so that it basically fills the screen?  For instance, when my browser is full screen it would have 8 columns but if I made my browser window smaller gridster would automatically reduce to 6 columns, etc.  It seems like there must be something simple I'm missing.

I have a div that is absolutely positioned with top, left, right and bottom set to 0px.  I'm then using add_widget() to add a few widgets with a for loop.  If I set max_cols to null, my div is the size I expect (full screen), but there are no widgets.  If I set max_cols to anything else, I get that many columns and my div is no longer full screen.

Hopefully this makes sense...

![image](https://cloud.githubusercontent.com/assets/108358/3054303/1e66b9f8-e1b6-11e3-893a-76472570939d.png)

**Comment by vieron** [comment] 2014-06-16 10:20
Duplicate of #5. Responsive grid is not supported by gridster.

**Closed as completed by vieron** 2014-06-16 10:20 UTC
